language: node_js
node_js:
- '0.12'
before_install:
- openssl aes-256-cbc -K $encrypted_b7cbdf137cf7_key -iv $encrypted_b7cbdf137cf7_iv
  -in travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- npm install -g webpack
install:
- npm install
before_script:
- webpack
- node dictionary.js
- if [ -f ./dictionary.json ]; then
    cp dictionary.json dist/
    git config --global user.email "kensplanet@yahoo.com"
    git config --global user.name "kensplanet"
    git checkout master
    git remote set-url origin git@github.com:kensplanet/dev-dictionary
    git add dictionary.json
    git commit -m "[skip ci] update dictionary"
    git push origin master
  fi

after_script: scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o
  PubkeyAuthentication=yes -o PasswordAuthentication=no index.html dist kensplanet@107.180.50.184:/home/kensplanet/public_html/dev-dictionary
