language: node_js
node_js:
- '0.12'
before_install:
- openssl aes-256-cbc -K $encrypted_b7cbdf137cf7_key -iv $encrypted_b7cbdf137cf7_iv
  -in travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- npm install -g webpack
install:
- npm install
before_script:
- webpack
- rm dictionary.json
- node dictionary.js
script: ./dictionary.sh
after_script: scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o
  PubkeyAuthentication=yes -o PasswordAuthentication=no index.html dist kensplanet@107.180.50.184:/home/kensplanet/public_html/dev-dictionary
